# Generated by Django 6.0.6 on 2026-06-10 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['city__name', 'name'], 'verbose_name': 'Район', 'verbose_name_plural': 'Районы'},
        ),
        migrations.AlterField(
            model_name='city',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название города'),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(help_text='Улица, номер дома', max_length=300, verbose_name='Полный адрес'),
        ),
        migrations.AlterField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(help_text='Опишите все особенности объекта', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='property',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='properties.district', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Отметьте, если объявление активно', verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='property',
            name='photos',
            field=models.JSONField(default=list, help_text='Список ссылок на фотографии', verbose_name='Фотографии'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Для посуточной аренды', max_digits=10, null=True, verbose_name='Цена за сутки (₽)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_per_month',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Для длительной аренды', max_digits=10, null=True, verbose_name='Цена за месяц (₽)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Квартира'), ('room', 'Комната'), ('house', 'Дом'), ('studio', 'Студия')], max_length=20, verbose_name='Тип объекта'),
        ),
        migrations.AlterField(
            model_name='property',
            name='rental_term',
            field=models.CharField(choices=[('daily', 'Посуточно'), ('long_term', 'Длительная'), ('both', 'Оба варианта')], default='both', max_length=20, verbose_name='Срок аренды'),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(help_text='Например: "Уютная квартира в центре"', max_length=200, verbose_name='Заголовок объявления'),
        ),
        migrations.AlterField(
            model_name='property',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
