# Generated by Django 6.0.6 on 2026-06-10 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_district_options_alter_city_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='photos',
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Загрузите фотографию объекта', upload_to='properties/%Y/%m/%d/', verbose_name='Фотография')),
                ('title', models.CharField(blank=True, help_text='Необязательное описание фото', max_length=100, verbose_name='Название фото')),
                ('is_main', models.BooleanField(default=False, help_text='Отметьте, если это главное фото объявления', verbose_name='Главное фото')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения фотографий', verbose_name='Порядок')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('property_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property', verbose_name='Объект недвижимости')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
