# Generated by Django 6.0.6 on 2026-06-10 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0002_alter_district_options_alter_city_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата заезда')),
                ('end_date', models.DateField(verbose_name='Дата выезда')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Автоматически рассчитывается', max_digits=10, verbose_name='Общая стоимость')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено'), ('completed', 'Завершено')], default='pending', max_length=20, verbose_name='Статус')),
                ('contract_signed', models.BooleanField(default=False, verbose_name='Договор подписан')),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='contracts/%Y/%m/%d/', verbose_name='Файл договора')),
                ('tenant_comment', models.TextField(blank=True, verbose_name='Комментарий арендатора')),
                ('owner_comment', models.TextField(blank=True, verbose_name='Комментарий владельца')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата бронирования')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('property_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='properties.property', verbose_name='Объект недвижимости')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Арендатор')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-created_at'],
                'unique_together': {('property_obj', 'start_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='UnavailableDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Недоступная дата')),
                ('reason', models.CharField(blank=True, help_text='Например: "Технические работы" или "Владелец занят"', max_length=200, verbose_name='Причина')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unavailable_dates', to='bookings.booking', verbose_name='Бронирование')),
                ('property_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailable_dates', to='properties.property', verbose_name='Объект недвижимости')),
            ],
            options={
                'verbose_name': 'Недоступная дата',
                'verbose_name_plural': 'Недоступные даты',
                'ordering': ['date'],
                'unique_together': {('property_obj', 'date')},
            },
        ),
    ]
