# Generated by Django 6.0.6 on 2026-06-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='booking',
            name='long_term_start_date',
            field=models.DateField(blank=True, help_text='Для долгосрочной аренды (бессрочно)', null=True, verbose_name='Дата начала долгосрочной аренды'),
        ),
        migrations.AddField(
            model_name='booking',
            name='nights_count',
            field=models.IntegerField(blank=True, help_text='Для посуточной аренды', null=True, verbose_name='Количество ночей'),
        ),
        migrations.AddField(
            model_name='booking',
            name='rental_type',
            field=models.CharField(choices=[('daily', 'Посуточно'), ('long_term', 'Длительная')], default='daily', max_length=20, verbose_name='Тип аренды'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateField(blank=True, help_text='Для посуточной аренды', null=True, verbose_name='Дата выезда'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.DateField(blank=True, help_text='Для посуточной аренды', null=True, verbose_name='Дата заезда'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, help_text='Для посуточной - общая сумма, для долгосрочной - цена за месяц', max_digits=10, verbose_name='Общая стоимость'),
        ),
    ]
