# Generated by Django 6.0.6 on 2026-06-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='owner_response_comment',
            field=models.TextField(blank=True, help_text='Комментарий при подтверждении или отказе бронирования', verbose_name='Комментарий владельца при ответе'),
        ),
    ]
